const USER_LOADING = "USER_LOADING";
const USER_AUTHORIZED = "USER_AUTHORIZED";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";

export default {
  USER_LOADING,
  USER_AUTHORIZED,
  LOGIN_ERROR,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGOUT_SUCCESS,
};
