const FETCH_POSTS = "FETCH_POSTS";
const POSTS_LOADING = "POSTS_LOADING";
const POSTS_ERROR = "POSTS_ERROR";
const CLEAR_POSTS = "CLEAR_POSTS";
const TOGGLE_LIKE_POST = "TOGGLE_LIKE_POST";

export default {
  FETCH_POSTS,
  POSTS_LOADING,
  POSTS_ERROR,
  CLEAR_POSTS,
  TOGGLE_LIKE_POST,
};
