const SELECTED_USER_LOADING = "SELECTED_USER_LOADING";
const SELECTED_USER_ERROR = "SELECTED_USER_ERROR";
const FETCH_SELECTED_USER = "FETCH_SELECTED_USER";
const USER_CLEAR_POSTS = "USER_CLEAR_POSTS";
const TOGGLE_LIKE_USER_POST = "TOGGLE_LIKE_USER_POST";
const TOGGLE_FOLLOW_USER = "TOGGLE_FOLLOW_USER";
const PUSH_USER = "PUSH_USER";
export default {
  SELECTED_USER_LOADING,
  SELECTED_USER_ERROR,
  FETCH_SELECTED_USER,
  USER_CLEAR_POSTS,
  TOGGLE_LIKE_USER_POST,
  TOGGLE_FOLLOW_USER,
  PUSH_USER,
};
