const SELECTED_USER_LOADING = "SELECTED_USER_LOADING";
const SELECTED_USER_ERROR = "SELECTED_USER_ERROR";
const FETCH_SELECTED_USER = "FETCH_SELECTED_USER";
const USER_CLEAR_POSTS = "USER_CLEAR_POSTS";
const TOGGLE_LIKE_USER_POST = "TOGGLE_LIKE_USER_POST";
const TOGGLE_FOLLOW_USER = "TOGGLE_FOLLOW_USER";
const PUSH_USER = "PUSH_USER";
const USER_FETCH_POSTS = "USER_FETCH_POSTS";
const USER_POSTS_LOADING = "USER_POSTS_LOADING";
const USER_POSTS_ERROR = "USER_POSTS_ERROR";
const ADD_IMAGE = "ADD_IMAGE";
const ADD_IMAGE_LOADING = "ADD_IMAGE_LOADING";
const REMOVE_IMAGE = "REMOVE_IMAGE";
export default {
  SELECTED_USER_LOADING,
  SELECTED_USER_ERROR,
  FETCH_SELECTED_USER,
  USER_CLEAR_POSTS,
  TOGGLE_LIKE_USER_POST,
  TOGGLE_FOLLOW_USER,
  PUSH_USER,
  USER_POSTS_ERROR,
  USER_POSTS_LOADING,
  USER_FETCH_POSTS,
  ADD_IMAGE,
  ADD_IMAGE_LOADING,
  REMOVE_IMAGE,
};
